name: Auto-assign PR author
on:
  pull_request:
    types: [opened]
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR author as assignee
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let author;
            if (context.payload.pull_request) {
              author = context.payload.pull_request.user?.login;
            } else if (context.payload.issue) {
              author = context.payload.issue.user?.login;
            }

            if (author) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [author]
              });
              console.log(`Assigned ${author} to issue/PR #${context.issue.number}`);
            } else {
              console.log("Author could not be determined.");
            }
