name: Auto-assign PR author
on:
  pull_request:
    types: [opened]
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR author as assignee
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [prAuthor]
            });
